export const UBIGEO_PERU = [
  {
    departamento: "LIMA",
    provincias: [
      {
        nombre: "LIMA",
        distritos: ["LIMA", "ANCON", "ATE", "BARRANCO", "BREÑA", "CARABAYLLO", "CHACLACAYO", "CHORRILLOS", "CIENEGUILLA", "COMAS", "EL AGUSTINO", "INDEPENDENCIA", "JESUS MARIA", "LA MOLINA", "LA VICTORIA", "LINCE", "LURIGANCHO", "LURIN", "MAGDALENA DEL MAR", "MIRAFLORES", "PACHACAMAC", "PUCUSANA", "PUEBLO LIBRE", "PUENTE PIEDRA", "PUNTA HERMOSA", "PUNTA NEGRA", "RIMAC", "SAN BARTOLO", "SAN BORJA", "SAN ISIDRO", "SAN JUAN DE LURIGANCHO", "SAN JUAN DE MIRAFORES", "SAN LUIS", "SAN MARTIN DE PORRES", "SAN MIGUEL", "SANTA ANITA", "SANTA MARIA DEL MAR", "SANTA ROSA", "SANTIAGO DE SURCO", "SURQUILLO", "VILLA EL SALVADOR", "VILLA MARIA DEL TRIUNFO"]
      },
      {
        nombre: "BARRANCA",
        distritos: ["BARRANCA", "PARAMONGA", "PATIVILCA", "PUERTO SUPE", "SUPE"]
      },
      {
        nombre: "CAÑETE",
        distritos: ["SAN VICENTE DE CAÑETE", "ASIA", "CALANGO", "CERRO AZUL", "CHILCA", "COAYLLO", "IMPERIAL", "LUNAHUANA", "MALA", "NUEVO IMPERIAL", "PACARAN", "QUILMANA", "SAN ANTONIO", "SAN LUIS", "SANTA CRUZ DE FLORES", "ZUÑIGA"]
      },
      {
        nombre: "HUARAL",
        distritos: ["HUARAL", "ATAVILLOS ALTO", "ATAVILLOS BAJO", "AUCALLAMA", "CHANCAY", "IHUARI", "LAMPIAN", "PACARAOS", "SANTA CRUZ DE ANDAMARCA", "SUMBILCA", "27 DE NOVIEMBRE"]
      },
      {
        nombre: "HUAURA",
        distritos: ["HUACHO", "AMBAR", "CALETA DE CARQUIN", "CHECRAS", "HUALMAY", "HUAURA", "LEONCIO PRADO", "PACCHO", "SANTA LEONOR", "SANTA MARIA", "SAYAN", "VEGUETA"]
      },
      {
        nombre: "HUAROCHIRI",
        distritos: ["MATUCANA", "ANTIOQUIA", "CALLAHUANCA", "CHICLA", "CUENCA", "HUACHUPAMPA", "HUANZA", "HUAROCHIRI", "LAHUAYTAMBO", "LANGA", "LARAOS", "MARIATANA", "RICARDO PALMA", "SAN ANDRES DE TUPICOCHA", "SAN ANTONIO", "SAN BARTOLOME", "SAN DAMIAN", "SAN JUAN DE IRIS", "SAN JUAN DE TANTARANCHE", "SAN LORENZO DE QUINTI", "SAN MATEO", "SAN MATEO DE OTAO", "SAN PEDRO DE CASTA", "SAN PEDRO DE HUANCAYRE", "SANGALLAYA", "SANTA CRUZ DE COCACHACRA", "SANTA EULALIA", "SANTIAGO DE ANCHUCAYA", "SANTIAGO DE TUNA", "SANTO DOMINGO DE LOS OLLEROS", "SURCO"]
      },
      { nombre: "CANTA", distritos: ["CANTA", "ARAHUAY", "HUAMANTANGA", "HUAROS", "LACHAQUI", "LINCHA", "SAN BUENAVENTURA"] },
      { nombre: "OYON", distritos: ["OYON", "ANDAJES", "CAUJUL", "COCHAMARCA", "NAVAN", "PACHANGARA"] },
      { nombre: "YAUYOS", distritos: ["YAUYOS", "ALIS", "AYAUCA", "AYAVIRI", "AZANGARO", "CACRA", "CARANIA", "CATAHUASI", "CHOCOS", "COCHAS", "COLONIA", "HONGOS", "HUAMPARA", "HUANEC", "HUANGASCAR", "HUANTAN", "HUAÑEC", "LARAOS", "LINCHA", "MADEAN", "MIRAFLORES", "OMAS", "PUTINZA", "QUINCHES", "QUINOCAY", "SAN JOAQUIN", "SAN PEDRO DE PILAS", "TANTA", "TAURIPAMPA", "TOMAS", "TUPE", "VIÑAC", "VITIS"] }
    ]
  },
  {
    departamento: "CALLAO",
    provincias: [
      {
        nombre: "CALLAO",
        distritos: ["CALLAO", "BELLAVISTA", "CARMEN DE LA LEGUA REYNOSO", "LA PERLA", "LA PUNTA", "VENTANILLA", "MI PERU"]
      }
    ]
  },
  {
    departamento: "AREQUIPA",
    provincias: [
      {
        nombre: "AREQUIPA",
        distritos: ["AREQUIPA", "ALTO SELVA ALEGRE", "CAYMA", "CERRO COLORADO", "CHARACATO", "CHIGUATA", "JACOBO HUNTER", "JOSE LUIS BUSTAMANTE Y RIVERO", "LA JOYA", "MARIANO MELGAR", "MIRAFLORES", "MOLLEBAYA", "PAUCARPATA", "POCSI", "POLOBAYA", "QUEQUEÑA", "SABANDIA", "SACHACA", "SAN JUAN DE SIGUAS", "SAN JUAN DE TARUCANI", "SANTA ISABEL DE SIGUAS", "SANTA RITA DE SIGUAS", "SOCABAYA", "TIABAYA", "UCHUMAYO", "VITOR", "YANAHUARA", "YARABAMBA", "YURA"]
      },
      { nombre: "CAMANA", distritos: ["CAMANA", "JOSE MARIA QUIMPER", "MARIANO NICOLAS VALCARCEL", "MARISCAL CACERES", "NICOLAS DE PIEROLA", "OCAÑA", "QUILCA", "SAMUEL PASTOR"] },
      { nombre: "CARAVELI", distritos: ["CARAVELI", "ACARI", "ATICO", "ATIQUIPA", "BELLA UNION", "CAHUACHO", "CHALA", "CHAPARRA", "HUANUHUANU", "JAQUI", "LOMAS", "QUICACHA", "YAUCA"] },
      { nombre: "CASTILLA", distritos: ["APLAO", "ANDAGUA", "AYO", "CHACHAS", "CHILCAYMARCA", "CHOCO", "HUANCARQUI", "MACHAGUAY", "ORCOPAMPA", "PAMPACOLCA", "TIPAN", "UÑON", "URACA", "VIRACO"] },
      { nombre: "CAYLLOMA", distritos: ["CHIVAY", "ACHOMA", "CABANACONDE", "CALLALLI", "CAYLLOMA", "COPORAQUE", "HUAMBO", "HUANCA", "ICHUPAMPA", "LARI", "LLUTA", "MACA", "MADRIGAL", "MAJES", "MURA", "PUYCA", "SIBAYO", "TAPAY", "TISCO", "TUTI", "YANQUE"] },
      { nombre: "CONDESUYOS", distritos: ["CHUQUIBAMBA", "ANDARAY", "CAYARANI", "CHICHAS", "IRAY", "RIO GRANDE", "SALAMANCA", "YANAQUIHUA"] },
      { nombre: "ISLAY", distritos: ["MOLLENDO", "COCACHACRA", "DEAN VALDIVIA", "ISLAY", "MEJIA", "PUNTA DE BOMBON"] },
      { nombre: "LA UNION", distritos: ["COTAHUASI", "ALCA", "CHARCANA", "HUAYNACOTAS", "PAMPAMARCA", "PUYCA", "QUECHUALLA", "SAYLA", "TAURIA", "TOMEPAMPA", "TORO"] }
    ]
  },
  {
    departamento: "LA LIBERTAD",
    provincias: [
      { nombre: "TRUJILLO", distritos: ["TRUJILLO", "EL PORVENIR", "FLORENCIA DE MORA", "HUANCHACO", "LA ESPERANZA", "LAREDO", "MOCHE", "POROTO", "SALAVERRY", "SIMBAL", "VICTOR LARCO HERRERA"] },
      { nombre: "ASCOPE", distritos: ["ASCOPE", "CASA GRANDE", "CHICAMA", "CHOCOPE", "MAGDALENA DE CAO", "PAIJAN", "RAZURI", "SANTIAGO DE CAO"] },
      { nombre: "BOLIVAR", distritos: ["BOLIVAR", "BAMBAMARCA", "CONDORMARCA", "LONGOTEA", "UCHUMARCA", "UCUNCHA"] },
      { nombre: "CHEPEN", distritos: ["CHEPEN", "PACANGA", "PUEBLO NUEVO"] },
      { nombre: "JULCAN", distritos: ["JULCAN", "CALAMARCA", "CARABAMBA", "HUASO"] },
      { nombre: "OTUZCO", distritos: ["OTUZCO", "AGALLPAMPA", "CHARAT", "HUARANCHAL", "LA CUESTA", "MACHE", "PARANDAY", "SALPO", "SINSICAP", "USQUIL"] },
      { nombre: "PACASMAYO", distritos: ["SAN PEDRO DE LLOC", "GUADALUPE", "JEQUETEPEQUE", "PACASMAYO", "SAN JOSE"] },
      { nombre: "PATAZ", distritos: ["TAYABAMBA", "BULDIBUYO", "CHILLIA", "HUANCASPATA", "HUAYLILLAS", "HUAYO", "ONGON", "PARCOY", "PATAZ", "PIAS", "SANTIAGO DE CHALLAS", "TAURIJA", "URPAY"] },
      { nombre: "SANCHEZ CARRION", distritos: ["HUAMACHUCO", "CHUGAY", "COCHORCO", "CURGOS", "MARCABAL", "SANAGORAN", "SARIN", "SARTIMBAMBA"] },
      { nombre: "SANTIAGO DE CHUCO", distritos: ["SANTIAGO DE CHUCO", "ANGASMARCA", "CACHICADAN", "MOLLEBAMBA", "MOLLEPATA", "QUIRUVILCA", "SANTA CRUZ DE CHUCA", "SITABAMBA"] },
      { nombre: "GRAN CHIMU", distritos: ["CASCAS", "LUCMA", "MARMOT", "SAYAPULLO"] },
      { nombre: "VIRU", distritos: ["VIRU", "CHAO", "GUADALUPITO"] }
    ]
  },
  {
    departamento: "LAMBAYEQUE",
    provincias: [
      { nombre: "CHICLAYO", distritos: ["CHICLAYO", "CAYALTI", "CHONGOYAPE", "ETEN", "ETEN PUERTO", "JOSE LEONARDO ORTIZ", "LA VICTORIA", "LAGUNAS", "MONSEFU", "NUEVA ARICA", "OYOTUN", "PATAPO", "PICSI", "PIMENTEL", "POMALCA", "PUCALA", "REQUE", "SANTA ROSA", "SAÑA", "TUMAN"] },
      { nombre: "FERREÑAFE", distritos: ["FERREÑAFE", "CAÑARIS", "INCAHUASI", "MANUEL ANTONIO MESONES MURO", "PITIPO", "PUEBLO NUEVO"] },
      { nombre: "LAMBAYEQUE", distritos: ["LAMBAYEQUE", "CHOCHOPE", "ILLIMO", "JAYANCA", "MOCHUMI", "MORROPE", "MOTUPE", "OLMOS", "PACORA", "SALAS", "SAN JOSE", "TUCUME"] }
    ]
  },
  {
    departamento: "PIURA",
    provincias: [
      { nombre: "PIURA", distritos: ["PIURA", "CASTILLA", "CATACAOS", "CURA MORI", "LA ARENA", "LA UNION", "LAS LOMAS", "TAMBO GRANDE", "VEINTISEIS DE OCTUBRE"] },
      { nombre: "AYABACA", distritos: ["AYABACA", "FRIAS", "JILILI", "LAGUNAS", "MONTERO", "PACAIPAMPA", "PAIMAS", "SAPILLICA", "SICCHEZ", "SUYO"] },
      { nombre: "HUANCABAMBA", distritos: ["HUANCABAMBA", "CANCHAQUE", "EL CARMEN DE LA FRONTERA", "HUARMACA", "LALAQUIZ", "SAN MIGUEL DE EL FAIQUE", "SONDOR", "SONDORILLO"] },
      { nombre: "PAITA", distritos: ["PAITA", "AMOTAPE", "ARENAL", "COLAN", "LA HUACA", "TAMARINDO", "VICHAYAL"] },
      { nombre: "SULLANA", distritos: ["SULLANA", "BELLAVISTA", "IGNACIO ESCUDERO", "LANCONES", "MARCAVELICA", "MIGUEL CHECA", "QUERECOTILLO", "SALITRAL"] },
      { nombre: "TALARA", distritos: ["PARIÑAS", "EL ALTO", "LA BREA", "LOBITOS", "LOS ORGANOS", "MANCORA"] },
      { nombre: "SECHURA", distritos: ["SECHURA", "BELLAVISTA DE LA UNION", "BERNAL", "CRISTO NOS VALGA", "RINCONADA LLICUAR", "VICE"] },
      { nombre: "MORROPON", distritos: ["CHULUCANAS", "BUENOS AIRES", "CHALACO", "LA MATANZA", "MORROPON", "SALITRAL", "SAN JUAN DE BIGOTE", "SANTA CATALINA DE MOSSA", "SANTO DOMINGO", "YAMANGO"] }
    ]
  },

  {
    departamento: "CUSCO",
    provincias: [
      { nombre: "CUSCO", distritos: ["CUSCO", "CCORCA", "POROY", "SAN JERONIMO", "SAN SEBASTIAN", "SANTIAGO", "SAYLLA", "WANCHAQ"] },
      { nombre: "ACOMAYO", distritos: ["ACOMAYO", "ACOPIA", "ACOS", "MOSOC LLACTA", "POMACANCHI", "RONDOCAN", "SANGARARA"] },
      { nombre: "ANTA", distritos: ["ANTA", "ANCAHUASI", "CACHIMAYO", "CHINCHAYPUQUIO", "HUAROCONDO", "LIMATAMBO", "MOLLEPATA", "PUYCA", "ZURITE"] },
      { nombre: "CALCA", distritos: ["CALCA", "COYA", "LAMAY", "LARES", "PISAC", "SAN SALVADOR", "TARAY", "YANATILE"] },
      { nombre: "CANAS", distritos: ["YANAOCA", "CHECCA", "KUNTURKANKI", "LANGUI", "LAYO", "PAMPAMARCA", "QUEHUE", "TUPAC AMARU"] },
      { nombre: "CANCHIS", distritos: ["SICUANI", "COMBAPATA", "CHECACUPE", "MARANGANI", "PITUMARCA", "SAN PABLO", "SAN PEDRO", "TINTA"] },
      { nombre: "CHUMBIVILCAS", distritos: ["SANTO TOMAS", "CAPACMARCA", "CHAMACA", "COLQUEMARCA", "LIVITACA", "LLUSCO", "QUIÑOTA", "VELILLE"] },
      { nombre: "ESPINAR", distritos: ["YAURI", "CONDOROMA", "COPORAQUE", "OCORURO", "PALLPATA", "PICHIGUA", "SUYCKUTAMBO", "ALTO PICHIGUA"] },
      { nombre: "LA CONVENCION", distritos: ["QUILLABAMBA", "ECHARATE", "HUAYOPATA", "MARANURA", "OCABAMBA", "QUELLOUNO", "QUIMBIRI", "SANTA ANA", "SANTA TERESA", "VILCABAMBA", "PICHARI", "INKAWASI", "VILLA VIRGEN", "VILLA KINTIARINA"] },
      { nombre: "PARURO", distritos: ["PARURO", "ACCHA", "CCAPI", "COLCHA", "HUANOQUITE", "OMACHA", "PACCARITAMBO", "PILLPINTO", "YAURISQUE"] },
      { nombre: "PAUCARTAMBO", distritos: ["PAUCARTAMBO", "CAICAY", "CHALLABAMBA", "COLQUEPATA", "HUANCARANI", "KOSÑIPATA"] },
      { nombre: "QUISPICANCHI", distritos: ["URCOS", "ANDAHUAYLILLAS", "CAMANTI", "CCARHUAYO", "CCATCA", "CUSIPATA", "HUARO", "LUCRE", "MARCAPATA", "OCONGATE", "OROPESA", "QUIQUIJANA"] },
      { nombre: "URUBAMBA", distritos: ["URUBAMBA", "CHINCHERO", "HUAYLLABAMBA", "MACHUPICCHU", "MARAS", "OLLANTAYTAMBO", "YUCAY"] }
    ]
  },
  {
    departamento: "PUNO",
    provincias: [
      { nombre: "PUNO", distritos: ["PUNO", "ACORA", "AMANTANI", "ATUNCOLLA", "CAPACHICA", "CHUCUITO", "COATA", "HUATA", "MAÑAZO", "PAUCOCOLLA", "PICHACANI", "PLATERIA", "SAN ANTONIO", "TIQUILLACA", "VILQUE"] },
      { nombre: "AZANGARO", distritos: ["AZANGARO", "ACHAYA", "ARAPA", "ASILLO", "CAMINACA", "CHUPA", "JOSE DOMINGO CHOQUEHUANCA", "MUÑANI", "POTONI", "SAMAN", "SAN ANTON", "SAN JOSE", "SAN JUAN DE SALINAS", "SANTIAGO DE PUPUJA", "TIRAPATA"] },
      { nombre: "CARABAYA", distritos: ["MACUSANI", "AJOYANI", "AYAPATA", "COASA", "CORANI", "CRUCERO", "ITUATA", "OLLACHEA", "SAN GABAN", "USICAYOS"] },
      { nombre: "CHUCUITO", distritos: ["JULI", "DESAGUADERO", "HUACULLANI", "KELLUYO", "PISACOMA", "POMATA", "ZEPITA"] },
      { nombre: "EL COLLAO", distritos: ["ILAVE", "CONDURIRI", "MAZOCRUZ", "PILCUYO", "SANTA ROSA"] },
      { nombre: "HUANCANE", distritos: ["HUANCANE", "COJATA", "HUATASANI", "INCHUPALLA", "Pusi", "ROSASPATA", "TARACO", "VILQUE CHICO"] },
      { nombre: "LAMPA", distritos: ["LAMPA", "CABANILLA", "CALAPUJA", "NICASIO", "OCUVIRI", "PALCA", "PARATIA", "PUCARA", "SANTA LUCIA", "VILAVILA"] },
      { nombre: "MELGAR", distritos: ["AYAVIRI", "ANTAUTA", "CUPI", "LLALLI", "MACARI", "NUÑOA", "ORURILLO", "SANTA ROSA", "UMACHIRI"] },
      { nombre: "MOHO", distritos: ["MOHO", "CONIMA", "TILALI", "HUAYRAPATA"] },
      { nombre: "SAN ANTONIO DE PUTINA", distritos: ["PUTINA", "ANANEA", "PEDRO VILCA APAZA", "QUILCAPUNCU", "SINA"] },
      { nombre: "SAN ROMAN", distritos: ["JULIACA", "CABANA", "CABANILLAS", "CARACOTO", "SAN MIGUEL"] },
      { nombre: "SANDIA", distritos: ["SANDIA", "CUYOCUYO", "LIMBANI", "PATAMBUCO", "PHARA", "QUIACA", "SAN JUAN DEL ORO", "YANAHUAYA", "ALTO INAMBARI", "SAN PEDRO DE PUTINA PUNCO"] },
      { nombre: "YUNGUYO", distritos: ["YUNGUYO", "ANAPIA", "COPACABANA", "CUTURAPI", "OLLARAYA", "TINICACHI", "UNICACHI"] }
    ]
  },
  {
    departamento: "ICA",
    provincias: [
      { nombre: "ICA", distritos: ["ICA", "LA TINGUIÑA", "LOS AQUIJES", "OCUCAJE", "PACHACUTEC", "PARCONA", "PUEBLO NUEVO", "SALAS", "SAN JOSE DE LOS MOLINOS", "SAN JUAN BAUTISTA", "SANTIAGO", "SUBTANJALLA", "TATE", "YAUCA DEL ROSARIO"] },
      { nombre: "CHINCHA", distritos: ["CHINCHA ALTA", "ALTO LARAN", "CHAVIN", "CHINCHA BAJA", "EL CARMEN", "EL RECREO", "GROCIO PRADO", "PUEBLO NUEVO", "SAN JUAN DE YANAC", "SAN PEDRO DE HUACARPANA", "SUNAMPE", "TAMBO DE MORA"] },
      { nombre: "NASCA", distritos: ["NASCA", "CHANGUILLO", "EL INGENIO", "MARCONA", "VISTA ALEGRE"] },
      { nombre: "PALPA", distritos: ["PALPA", "LLIPATA", "RIO GRANDE", "SANTA CRUZ", "TIBILLO"] },
      { nombre: "PISCO", distritos: ["PISCO", "HUANCANO", "HUMAY", "INDEPENDENCIA", "PARACAS", "SAN ANDRES", "SAN CLEMENTE", "TUPAC AMARU INCA"] }
    ]
  },

  {
    departamento: "JUNIN",
    provincias: [
      { nombre: "HUANCAYO", distritos: ["HUANCAYO", "CARHUACALLANGA", "CHACAPAMPA", "CHICCHE", "CHILCA", "CHUPURO", "COLCA", "CULLHUAS", "EL TAMBO", "HUACRAPUQUIO", "HUALHUAS", "HUANCAN", "HUASICANCHA", "HUAYUCACHI", "INGENIO", "PARIAHUANCA", "PILCOMAYO", "PUCARA", "QUICHUAY", "QUILCAS", "SAN AGUSTIN", "SAN JERONIMO DE TUNAN", "SAÑO", "SAPALLANGA", "SICAYA", "SANTO DOMINGO DE ACOBAMBA", "VIQUES"] },
      { nombre: "CHANCHAMAYO", distritos: ["LA MERCED", "PICHANAQUI", "SAN LUIS DE SHUARO", "SAN RAMON", "VITOC", "PERENE"] },
      { nombre: "CHUPACA", distritos: ["CHUPACA", "AHUAC", "CHONGOS BAJO", "HUACHAC", "HUAMANCACA CHICO", "SAN JUAN DE ISCOS", "SAN JUAN DE JARPA", "TRES DE DICIEMBRE", "YANACANCHA"] },
      { nombre: "CONCEPCION", distritos: ["CONCEPCION", "ACO", "ANDAMARCA", "CHAMBARA", "COCHAS", "COMAS", "HEROINAS TOLEDO", "MANZANARES", "MARISCAL CASTILLA", "MATAHUASI", "MITO", "NUEVE DE JULIO", "ORCOTUNA", "SAN JOSE DE QUERO", "SANTA ROSA DE OCOPA"] },
      { nombre: "JAUJA", distritos: ["JAUJA", "ACOLLA", "APATA", "ATAURA", "CANCHAYLLO", "CURICACA", "EL MANTARO", "HUAMALI", "HUARIPAMPA", "HUERTAS", "JANJAILLO", "JULCAN", "LEONOR ORDOÑEZ", "LLOCLLAPAMPA", "MARCO", "MASMA", "MASMA CHICCHE", "MOLINOS", "MONOBAMBA", "MUQUI", "MUQUIYAUYO", "PACA", "PACCHA", "PANCAN", "PARCO", "POMACANCHA", "RICRAN", "SAN LORENZO", "SAN PEDRO DE CHUNAN", "SAUSA", "SINCOS", "TUNAN MARCA", "YAULI", "YAUYOS"] },
      { nombre: "JUNIN", distritos: ["JUNIN", "CARHUAMAYO", "ONDORES", "ULCUMAYO"] },
      { nombre: "SATIPO", distritos: ["SATIPO", "COVIRIALI", "LLAYLLA", "MAZAMARI", "PAMPA HERMOSA", "PANGOA", "RIO NEGRO", "RIO TAMBO", "VIZCATAN DEL ENE"] },
      { nombre: "TARMA", distritos: ["TARMA", "ACOBAMBA", "HUARICOLCA", "HUASAHUASI", "LA UNION", "PALCA", "PALCAMAYO", "SAN PEDRO DE CAJAS", "TAPO"] },
      { nombre: "YAULI", distritos: ["LA OROYA", "CHACAPALPA", "HUAY-HUAY", "MARCAPOMACOCHA", "MOROCOCHA", "PACCHA", "SANTA BARBARA DE CARHUACAYAN", "SANTA ROSA DE SACCO", "SUITUCANCHA", "YAULI"] }
    ]
  },
  {
    departamento: "LORETO",
    provincias: [
      { nombre: "MAYNAS", distritos: ["IQUITOS", "ALTO NANAY", "FERNANDO LORES", "INDIANA", "LAS AMAZONAS", "MAZAN", "NAPO", "PUNCHANA", "PUTUMAYO", "TORRES CAUSANA", "BELEN", "SAN JUAN BAUTISTA"] },
      { nombre: "ALTO AMAZONAS", distritos: ["YURIMAGUAS", "BALSAPUERTO", "JEBEROS", "LAGUNAS", "SANTA CRUZ", "TENIENTE CESAR LOPEZ ROJAS"] },
      { nombre: "DATEM DEL MARAÑON", distritos: ["BARRANCA", "CAHUAPANAS", "MANSERICHE", "MORONA", "PASTAZA", "ANDOAS"] },
      { nombre: "LORETO", distritos: ["NAUTA", "PARINARI", "TIGRE", "TROMPETEROS", "URARINAS"] },
      { nombre: "MARISCAL RAMON CASTILLA", distritos: ["RAMON CASTILLA", "PEBAS", "YAVARI", "SAN PABLO"] },
      { nombre: "REQUENA", distritos: ["REQUENA", "ALTO TAPICHE", "CAPELO", "EMILIO SAN MARTIN", "MAQUIA", "PUINAHUA", "SAQUENA", "SOPLIN", "TAPICHE", "JENARO HERRERA", "YAQUERANA"] },
      { nombre: "UCAYALI", distritos: ["CONTAMANA", "INAHUAYA", "PADRE MARQUEZ", "PAMPA HERMOSA", "SARAYACU", "VARGAS GUERRA"] }
    ]
  },
  {
    departamento: "UCAYALI",
    provincias: [
      { nombre: "CORONEL PORTILLO", distritos: ["CALLERIA", "CAMPOVERDE", "IPARIA", "MASISEA", "YARINACOCHA", "NUEVA REQUENA", "MANANTAY"] },
      { nombre: "ATALAYA", distritos: ["RAYMONDI", "SEPAHUA", "TAHUANIA", "YURUA"] },
      { nombre: "PADRE ABAD", distritos: ["PADRE ABAD", "IRAZOLA", "CURIMANA", "NESHUYA", "ALEXANDER VON HUMBOLDT"] },
      { nombre: "PURUS", distritos: ["PURUS"] }
    ]
  },
  {
    departamento: "SAN MARTIN",
    provincias: [
      { nombre: "MOYOBAMBA", distritos: ["MOYOBAMBA", "CALZADA", "HABANA", "JEPELACIO", "SORITOR", "YANTALO"] },
      { nombre: "BELLAVISTA", distritos: ["BELLAVISTA", "ALTO BIAVO", "BAJO BIAVO", "HUALLAGA", "MAZAN", "SAN PABLO", "SAN RAFAEL"] },
      { nombre: "EL DORADO", distritos: ["SAN JOSE DE SISA", "AGUA BLANCA", "SAN MARTIN", "SANTA ROSA", "SHATOJA"] },
      { nombre: "HUALLAGA", distritos: ["SAPOSOA", "ALTO SAPOSOA", "EL ESLABON", "PISCOYACU", "SACANCHE", "TINGO DE SAPOSOA"] },
      { nombre: "LAMAS", distritos: ["LAMAS", "ALONSO DE ALVARADO", "BARRANQUITA", "CAYNARACHI", "CUÑUMBUQUI", "PINTO RECOVAR", "RUMISAPA", "SAN ROQUE DE CUMBAZA", "SHANAO", "TABALOSOS", "ZAPATERO"] },
      { nombre: "MARISCAL CACERES", distritos: ["JUANJUI", "CAMPANILLA", "HUICUNGO", "PACHIZA", "PAJARILLO"] },
      { nombre: "PICOTA", distritos: ["PICOTA", "BUENOS AIRES", "CASPISAPA", "PILLUANA", "PUCACACA", "SAN CRISTOBAL", "SAN HILARION", "TINGO DE PONASA"] },
      { nombre: "RIOJA", distritos: ["RIOJA", "AWAJUN", "ELIAS SOPLIN VARGAS", "NUEVA CAJAMARCA", "PARDO MIGUEL", "POSIC", "SAN FERNANDO", "YORONGOS", "YURACYACU"] },
      { nombre: "SAN MARTIN", distritos: ["TARAPOTO", "ALBERTO LEVEAU", "CACATACHI", "CHAZUTA", "CHIPURANA", "EL PORVENIR", "HUIMBAYOC", "JUAN GUERRA", "MORALES", "PAPAPLAYA", "SAN ANTONIO", "SAUCE", "SHAPAJA"] },
      { nombre: "TOCACHE", distritos: ["TOCACHE", "NUEVO PROGRESO", "POLVORA", "SHUNTE", "UCHIZA"] }
    ]
  },

  {
    departamento: "JUNIN",
    provincias: [
      { nombre: "HUANCAYO", distritos: ["HUANCAYO", "CARHUACALLANGA", "CHACAPAMPA", "CHICCHE", "CHILCA", "CHUPURO", "COLCA", "CULLHUAS", "EL TAMBO", "HUACRAPUQUIO", "HUALHUAS", "HUANCAN", "HUASICANCHA", "HUAYUCACHI", "INGENIO", "PARIAHUANCA", "PILCOMAYO", "PUCARA", "QUICHUAY", "QUILCAS", "SAN AGUSTIN", "SAN JERONIMO DE TUNAN", "SAÑO", "SAPALLANGA", "SICAYA", "SANTO DOMINGO DE ACOBAMBA", "VIQUES"] },
      { nombre: "CHANCHAMAYO", distritos: ["LA MERCED", "PICHANAQUI", "SAN LUIS DE SHUARO", "SAN RAMON", "VITOC", "PERENE"] },
      { nombre: "CHUPACA", distritos: ["CHUPACA", "AHUAC", "CHONGOS BAJO", "HUACHAC", "HUAMANCACA CHICO", "SAN JUAN DE ISCOS", "SAN JUAN DE JARPA", "TRES DE DICIEMBRE", "YANACANCHA"] },
      { nombre: "CONCEPCION", distritos: ["CONCEPCION", "ACO", "ANDAMARCA", "CHAMBARA", "COCHAS", "COMAS", "HEROINAS TOLEDO", "MANZANARES", "MARISCAL CASTILLA", "MATAHUASI", "MITO", "NUEVE DE JULIO", "ORCOTUNA", "SAN JOSE DE QUERO", "SANTA ROSA DE OCOPA"] },
      { nombre: "JAUJA", distritos: ["JAUJA", "ACOLLA", "APATA", "ATAURA", "CANCHAYLLO", "CURICACA", "EL MANTARO", "HUAMALI", "HUARIPAMPA", "HUERTAS", "JANJAILLO", "JULCAN", "LEONOR ORDOÑEZ", "LLOCLLAPAMPA", "MARCO", "MASMA", "MASMA CHICCHE", "MOLINOS", "MONOBAMBA", "MUQUI", "MUQUIYAUYO", "PACA", "PACCHA", "PANCAN", "PARCO", "POMACANCHA", "RICRAN", "SAN LORENZO", "SAN PEDRO DE CHUNAN", "SAUSA", "SINCOS", "TUNAN MARCA", "YAULI", "YAUYOS"] },
      { nombre: "JUNIN", distritos: ["JUNIN", "CARHUAMAYO", "ONDORES", "ULCUMAYO"] },
      { nombre: "SATIPO", distritos: ["SATIPO", "COVIRIALI", "LLAYLLA", "MAZAMARI", "PAMPA HERMOSA", "PANGOA", "RIO NEGRO", "RIO TAMBO", "VIZCATAN DEL ENE"] },
      { nombre: "TARMA", distritos: ["TARMA", "ACOBAMBA", "HUARICOLCA", "HUASAHUASI", "LA UNION", "PALCA", "PALCAMAYO", "SAN PEDRO DE CAJAS", "TAPO"] },
      { nombre: "YAULI", distritos: ["LA OROYA", "CHACAPALPA", "HUAY-HUAY", "MARCAPOMACOCHA", "MOROCOCHA", "PACCHA", "SANTA BARBARA DE CARHUACAYAN", "SANTA ROSA DE SACCO", "SUITUCANCHA", "YAULI"] }
    ]
  },
  {
    departamento: "LORETO",
    provincias: [
      { nombre: "MAYNAS", distritos: ["IQUITOS", "ALTO NANAY", "FERNANDO LORES", "INDIANA", "LAS AMAZONAS", "MAZAN", "NAPO", "PUNCHANA", "PUTUMAYO", "TORRES CAUSANA", "BELEN", "SAN JUAN BAUTISTA"] },
      { nombre: "ALTO AMAZONAS", distritos: ["YURIMAGUAS", "BALSAPUERTO", "JEBEROS", "LAGUNAS", "SANTA CRUZ", "TENIENTE CESAR LOPEZ ROJAS"] },
      { nombre: "DATEM DEL MARAÑON", distritos: ["BARRANCA", "CAHUAPANAS", "MANSERICHE", "MORONA", "PASTAZA", "ANDOAS"] },
      { nombre: "LORETO", distritos: ["NAUTA", "PARINARI", "TIGRE", "TROMPETEROS", "URARINAS"] },
      { nombre: "MARISCAL RAMON CASTILLA", distritos: ["RAMON CASTILLA", "PEBAS", "YAVARI", "SAN PABLO"] },
      { nombre: "REQUENA", distritos: ["REQUENA", "ALTO TAPICHE", "CAPELO", "EMILIO SAN MARTIN", "MAQUIA", "PUINAHUA", "SAQUENA", "SOPLIN", "TAPICHE", "JENARO HERRERA", "YAQUERANA"] },
      { nombre: "UCAYALI", distritos: ["CONTAMANA", "INAHUAYA", "PADRE MARQUEZ", "PAMPA HERMOSA", "SARAYACU", "VARGAS GUERRA"] }
    ]
  },
  {
    departamento: "UCAYALI",
    provincias: [
      { nombre: "CORONEL PORTILLO", distritos: ["CALLERIA", "CAMPOVERDE", "IPARIA", "MASISEA", "YARINACOCHA", "NUEVA REQUENA", "MANANTAY"] },
      { nombre: "ATALAYA", distritos: ["RAYMONDI", "SEPAHUA", "TAHUANIA", "YURUA"] },
      { nombre: "PADRE ABAD", distritos: ["PADRE ABAD", "IRAZOLA", "CURIMANA", "NESHUYA", "ALEXANDER VON HUMBOLDT"] },
      { nombre: "PURUS", distritos: ["PURUS"] }
    ]
  },
  {
    departamento: "SAN MARTIN",
    provincias: [
      { nombre: "MOYOBAMBA", distritos: ["MOYOBAMBA", "CALZADA", "HABANA", "JEPELACIO", "SORITOR", "YANTALO"] },
      { nombre: "BELLAVISTA", distritos: ["BELLAVISTA", "ALTO BIAVO", "BAJO BIAVO", "HUALLAGA", "MAZAN", "SAN PABLO", "SAN RAFAEL"] },
      { nombre: "EL DORADO", distritos: ["SAN JOSE DE SISA", "AGUA BLANCA", "SAN MARTIN", "SANTA ROSA", "SHATOJA"] },
      { nombre: "HUALLAGA", distritos: ["SAPOSOA", "ALTO SAPOSOA", "EL ESLABON", "PISCOYACU", "SACANCHE", "TINGO DE SAPOSOA"] },
      { nombre: "LAMAS", distritos: ["LAMAS", "ALONSO DE ALVARADO", "BARRANQUITA", "CAYNARACHI", "CUÑUMBUQUI", "PINTO RECOVAR", "RUMISAPA", "SAN ROQUE DE CUMBAZA", "SHANAO", "TABALOSOS", "ZAPATERO"] },
      { nombre: "MARISCAL CACERES", distritos: ["JUANJUI", "CAMPANILLA", "HUICUNGO", "PACHIZA", "PAJARILLO"] },
      { nombre: "PICOTA", distritos: ["PICOTA", "BUENOS AIRES", "CASPISAPA", "PILLUANA", "PUCACACA", "SAN CRISTOBAL", "SAN HILARION", "TINGO DE PONASA"] },
      { nombre: "RIOJA", distritos: ["RIOJA", "AWAJUN", "ELIAS SOPLIN VARGAS", "NUEVA CAJAMARCA", "PARDO MIGUEL", "POSIC", "SAN FERNANDO", "YORONGOS", "YURACYACU"] },
      { nombre: "SAN MARTIN", distritos: ["TARAPOTO", "ALBERTO LEVEAU", "CACATACHI", "CHAZUTA", "CHIPURANA", "EL PORVENIR", "HUIMBAYOC", "JUAN GUERRA", "MORALES", "PAPAPLAYA", "SAN ANTONIO", "SAUCE", "SHAPAJA"] },
      { nombre: "TOCACHE", distritos: ["TOCACHE", "NUEVO PROGRESO", "POLVORA", "SHUNTE", "UCHIZA"] }
    ]
  },

  {
    departamento: "HUANUCO",
    provincias: [
      { nombre: "HUANUCO", distritos: ["HUANUCO", "AMARILIS", "CHINCHAO", "CHURUBAMBA", "MARGOS", "QUISQUI", "SAN FRANCISCO DE CAYRAN", "SAN PEDRO DE CHAULAN", "SANTA MARIA DEL VALLE", "YARUMAYO", "PILLCO MARCA"] },
      { nombre: "AMBO", distritos: ["AMBO", "CAYNA", "COLPAS", "CONCHAMARCA", "HUACAR", "SAN FRANCISCO", "SAN RAFAEL", "TOMAY KICHWA"] },
      { nombre: "DOS DE MAYO", distritos: ["LA UNION", "CHUQUIS", "MARIAS", "PACHAS", "QUIVILLA", "RIPAN", "SHUNQUI", "SILLAPATA", "YANAS"] },
      { nombre: "HUACAYBAMBA", distritos: ["HUACAYBAMBA", "CANCHABAMBA", "COCHABAMBA", "PINRA"] },
      { nombre: "HUAMALIES", distritos: ["LLATA", "ARANCAY", "CHAVIN DE PARIARARCA", "JACAS GRANDE", "JIRCAN", "MONZON", "PUNCHAO", "PUÑOS", "SINGA", "TANTAMAYO"] },
      { nombre: "LEONCIO PRADO", distritos: ["TINGO MARIA", "DANIEL ALOMIA ROBLES", "HERMILIO VALDIZAN", "JOSE CRESPO Y CASTILLO", "LUYANDO", "MARIANO DAMASO BERAUN"] },
      { nombre: "MARAÑON", distritos: ["HUACRACHUCO", "CHOLON", "SAN BUENAVENTURA"] },
      { nombre: "PACHITEA", distritos: ["PANAO", "CHAGLLA", "MOLINO", "UMARI"] },
      { nombre: "PUERTO INCA", distritos: ["PUERTO INCA", "CODO DEL POZUZO", "HONORIA", "PUERTO BERMUDEZ", "YUYAPICHIS"] },
      { nombre: "LAURICOCHA", distritos: ["JESUS", "BAÑOS", "JIVIA", "QUEROPALCA", "RONDOS", "SAN FRANCISCO DE ASIS", "SAN MIGUEL DE CAURI"] },
      { nombre: "YAROWILCA", distritos: ["CHAVINILLO", "CÁHUAC", "CHACABAMBA", "APARICIO POMAREST", "JACAS CHICO", "OBAS", "PAMPAMARCA", "CHORAS"] }
    ]
  },
  {
    departamento: "PASCO",
    provincias: [
      { nombre: "PASCO", distritos: ["CHAUPIMARCA", "HUACHON", "HUARIACA", "HUAYLLAY", "NINACACA", "PALLANCHACRA", "PAUCARTAMBO", "SAN FRANCISCO DE ASIS DE YARUSYACAN", "SIMON BOLIVAR", "TICLACAYAN", "TINYAHUARCO", "VICCO", "YANACANCHA"] },
      { nombre: "DANIEL ALCIDES CARRION", distritos: ["YANAHUANCA", "CHACAYAN", "GOYLLARISQUIZGA", "PAUCAR", "SAN PEDRO DE PILLAO", "SANTA ANA DE TUSI", "TAPUC", "VILCABAMBA"] },
      { nombre: "OXAPAMPA", distritos: ["OXAPAMPA", "CHONTABAMBA", "HUANCABAMBA", "PALCAZU", "POZUZO", "PUERTO BERMUDEZ", "VILLA RICA"] }
    ]
  },
  {
    departamento: "APURIMAC",
    provincias: [
      { nombre: "ABANCAY", distritos: ["ABANCAY", "CHACOCHE", "CIRCA", "CURAHUASI", "HUANIPACA", "LAMBRAMA", "PICHIRHUA", "SAN RAMON DE KEYLLIAPATA", "TAMBURCO"] },
      { nombre: "ANDAHUAYLAS", distritos: ["ANDAHUAYLAS", "ANDARAPA", "CHIARA", "HUANCARAMA", "HUANCARAY", "HUAYANA", "KISHUARA", "PACOBAMBA", "PACUCHA", "PAMPACHIRI", "POMACOCHA", "SAN ANTONIO DE CACHI", "SAN JERONIMO", "SAN MIGUEL DE CHACCRAMPA", "SANTA MARIA DE CHICMO", "TALAVERA", "TUMAY HUARACA", "TURPO", "KAQUIABAMBA"] },
      { nombre: "ANTABAMBA", distritos: ["ANTABAMBA", "EL ORO", "HUAQUIRCA", "JUAN ESPINOZA MEDRANO", "OROPESA", "PACHACONAS", "SABAYNO"] },
      { nombre: "AYMARAES", distritos: ["CHALHUANCA", "CAPAYA", "CARAYBAMBA", "CHAPIMARCA", "COLCABAMBA", "COTARUSE", "HUAYLLO", "JUSTO APU SAHUARAURA", "LUCRE", "POCOHUANCA", "SAN JUAN DE CHACÑA", "SAÑAYCA", "SORAYA", "TAPAIRIHUA", "TINTAY", "TORAYA"] },
      { nombre: "COTABAMBAS", distritos: ["TAMBOBAMBA", "COTABAMBAS", "COYLLURQUI", "HAQUIRA", "MARA", "CHALLHUAHUACHO"] },
      { nombre: "GRAU", distritos: ["CHUQUIBAMBILLA", "CURPASCU", "CURASCO", "GREGORIO PITA", "HUAYLLATI", "MAMARA", "MARISCAL GAMARRA", "MICAELA BASTIDAS", "PROGRESO", "SAN ANTONIO", "SANTA ROSA", "TURPAY", "VILCABAMBA", "VIRUNDO"] },
      { nombre: "CHINCHEROS", distritos: ["CHINCHEROS", "ANCO_HUALLO", "COCHARCAS", "HUACCANA", "OCOBAMBA", "ONGOY", "URANMARCA", "RANRACANCHA"] }
    ]
  },
  {
    departamento: "AMAZONAS",
    provincias: [
      { nombre: "CHACHAPOYAS", distritos: ["CHACHAPOYAS", "ASUNCION", "BALSAS", "CHETO", "CHILIQUIN", "CHUQUIBAMBA", "GRANADA", "HUANCAS", "LA JALCA", "LEYMEBAMBA", "LEVANTO", "MAGDALENA", "MARISCAL CASTILLA", "MOLINOPAMPA", "MONTEVIDEO", "OLLEROS", "QUINJALCA", "SAN FRANCISCO DE DAGUAS", "SAN ISIDRO DE MAINO", "SOLOCO", "SONCHE"] },
      { nombre: "BAGUA", distritos: ["BAGUA", "ARAMANGO", "COPALLIN", "EL PARCO", "IMAZA", "LA PECA"] },
      { nombre: "BONGARA", distritos: ["JUMBILLA", "CHISQUILLA", "CHURUJA", "COROSHA", "CUISPES", "FLORIDA", "JAZAN", "RECTA", "SAN CARLOS", "SHIPASBAMBA", "VALERA", "YAMBRASBAMBA"] },
      { nombre: "CONDORCANQUI", distritos: ["NIEVA", "EL CENEPA", "RIO SANTIAGO"] },
      { nombre: "LUYA", distritos: ["LAMUD", "CAMPORREDONDO", "COCABAMBA", "COLCAMAR", "CONILA", "INGUILPATA", "LONGUITA", "LONYA CHICO", "LUYA", "LUYA VIEJO", "MARIA", "OCALLI", "OCUMAL", "PISUQUIA", "PROVIDENCIA", "SAN CRISTOBAL", "SAN FRANCISCO DEL YESO", "SAN JERONIMO", "SAN JUAN DE LOPECANCHA", "SANTA CATALINA", "SANTO TOMAS", "TINGO", "TRITA"] },
      { nombre: "RODRIGUEZ DE MENDOZA", distritos: ["SAN NICOLAS", "CHIRIMOTO", "COCHAMAL", "HUAMBO", "LIMABAMBA", "LONGAR", "MARISCAL BENAVIDES", "MILPUC", "OMIA", "SANTA ROSA", "TOTORA", "VISTA ALEGRE"] },
      { nombre: "UTCUBAMBA", distritos: ["BAGUA GRANDE", "CAJARURO", "CUMBA", "EL MILAGRO", "JAMALCA", "LONYA GRANDE", "YAMON"] }
    ]
  },
  {
    departamento: "MADRE DE DIOS",
    provincias: [
      { nombre: "TAMBOPATA", distritos: ["PUERTO MALDONADO", "INAMBARI", "LAS PIEDRAS", "LABERINTO"] },
      { nombre: "MANU", distritos: ["MANU", "FITZCARRALD", "MADRE DE DIOS", "HUEPETUHE"] },
      { nombre: "TAHUAMANU", distritos: ["IÑAPARI", "IBERIA", "TAHUAMANU"] }
    ]
  },
  {
    departamento: "MOQUEGUA",
    provincias: [
      { nombre: "MARISCAL NIETO", distritos: ["MOQUEGUA", "CARUMAS", "CUCHUMBAYA", "SAMEGUA", "SAN CRISTOBAL", "TORATA"] },
      { nombre: "GENERAL SANCHEZ CERRO", distritos: ["OMATE", "CHOJATA", "COALAQUE", "ICHUÑA", "LA CAPILLA", "LLUCO", "MATALAQUE", "PUQUINA", "QUINISTAQUILLAS", "UBINAS", "YUNGA"] },
      { nombre: "ILO", distritos: ["ILO", "EL ALGARROBAL", "PACOCHA"] }
    ]
  },
  {
    departamento: "TACNA",
    provincias: [
      { nombre: "TACNA", distritos: ["TACNA", "ALTO DE LA ALIANZA", "CALANA", "CIUDAD NUEVA", "INCLAN", "PACHIA", "PALCA", "POCOLLAY", "SAMA", "CORONEL GREGORIO ALBARRACIN LANCHIPA", "LA YARADA LOS PALOS"] },
      { nombre: "CANDARAVE", distritos: ["CANDARAVE", "CAIRANI", "CAMILACA", "CURIBAYA", "HUANUARA", "QUILAHUANI"] },
      { nombre: "JORGE BASADRE", distritos: ["LOCUMBA", "ILABAYA", "ITE"] },
      { nombre: "TARATA", distritos: ["TARATA", "CHUCATAMANI", "ESTIQUE", "ESTIQUE-PAMPA", "SITAJARA", "SUSAPAYA", "TICACO", "TARUCACHI"] }
    ]
  },
  {
    departamento: "TUMBES",
    provincias: [
      { nombre: "TUMBES", distritos: ["TUMBES", "CORRALES", "LA CRUZ", "PAMPAS DE HOSPITAL", "SAN JACINTO", "SAN JUAN DE LA VIRGEN"] },
      { nombre: "CONTRALMIRANTE VILLAR", distritos: ["ZORRITOS", "CASITAS", "CANOAS DE PUNTA SAL"] },
      { nombre: "ZARUMILLA", distritos: ["ZARUMILLA", "AGUAS VERDES", "MATAPALO", "PAPAYAL"] }
    ]
  }
];

  

  


















































































































































































