CREATE TABLE cupones (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    codigo TEXT UNIQUE NOT NULL, -- Aquí irá el formato FJ4J-FJD5-FJGN-FJ53
    descuento DECIMAL NOT NULL,  
    estado BOOLEAN DEFAULT TRUE, 
    creado_en TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    usado_por_dni TEXT, -- Opcional: para trackear quién lo usó
    expira_en TIMESTAMP WITH TIME ZONE 
);

-- Insertar cupones de 20 soles
INSERT INTO cupones (codigo, descuento, estado) 
VALUES 
('H3K9-J2L5-N8P1-W6X4', 20.00, true),
('A7Z2-M9Q6-R4V8-K1Y3', 20.00, true),
('B5X1-D4G7-H9J2-L0N6', 20.00, true);

-- Insertar cupones de 40 soles
INSERT INTO cupones (codigo, descuento, estado) 
VALUES 
('TR8W-Q2P5-N9M1-Z4V7', 40.00, true),
('F6G3-K9L0-X2B5-D8H1', 40.00, true),
('S1Y4-R7T9-P3N6-J5K2', 40.00, true);