-- 1. Creamos una tabla nueva con el orden lógico y profesional
CREATE TABLE modelos_nuevo (
  id int8 GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  sigla text UNIQUE,                  -- F0123
  modelo_nombre text NOT NULL,        -- Nombre real (ej. Bridge Plomo)
  precio numeric(10, 2) NOT NULL,
  descripcion text,
  color text,
  genero text,                        -- Hombre / Mujer / Unisex
  categoria text,
  -- Bloque de imágenes alineado
  imagen_url text,                    -- Principal
  imagen_url_2 text,
  imagen_url_3 text,
  imagen_url_4 text,
  imagen_url_5 text,
  created_at timestamp DEFAULT now()
);

-- 2. Pasamos los datos de la tabla vieja a la nueva
-- (Asegúrate de que los nombres coincidan con los que tienes actualmente)
INSERT INTO modelos_nuevo (id, modelo_nombre, precio, imagen_url, created_at)
SELECT id, nombre, precio, imagen_url, created_at 
FROM modelos;

-- 3. Borramos la tabla desordenada y renombramos la nueva
DROP TABLE modelos CASCADE; 
ALTER TABLE modelos_nuevo RENAME TO modelos;

-- 4. Re-vinculamos la tabla de stock (por si se rompió la relación)
ALTER TABLE variantes_stock 
  ADD CONSTRAINT variantes_stock_modelo_id_fkey 
  FOREIGN KEY (modelo_id) REFERENCES modelos(id) ON DELETE CASCADE;

  