CREATE TABLE direcciones (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    usuario_email TEXT NOT NULL,
    etiqueta TEXT DEFAULT 'CASA',
    direccion TEXT NOT NULL,
    referencia TEXT,
    distrito TEXT,
    es_principal BOOLEAN DEFAULT false,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),

    -- Ahora esta línea ya no dará error
    CONSTRAINT fk_usuario
      FOREIGN KEY(usuario_email) 
      REFERENCES usuarios(email)
      ON DELETE CASCADE
);

-- Seguridad RLS
ALTER TABLE direcciones ENABLE ROW LEVEL SECURITY;

-- Política de acceso (Criterio: que el usuario solo vea lo suyo)
CREATE POLICY "Gestión propia de direcciones" 
ON direcciones 
FOR ALL 
TO anon, authenticated 
USING (usuario_email = auth.jwt() ->> 'email');