CREATE TABLE IF NOT EXISTS variantes_stock (
  id int8 GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  modelo_id int8 REFERENCES modelos(id) ON DELETE CASCADE,
  talla int2 NOT NULL,
  stock int4 DEFAULT 0,
  created_at timestamp DEFAULT now()
);
