-- PASO 1: Volamos la tabla rota con todas sus políticas conflictivas
DROP TABLE IF EXISTS favoritos CASCADE;

-- PASO 2: Creamos la tabla limpia con el user_id tipo TEXT para tu ID "8"
CREATE TABLE favoritos (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id TEXT NOT NULL,       
    producto_id TEXT NOT NULL,   
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- Desactivamos el RLS para que Postgres no te vuelva a tirar carteles rojos de permisos
ALTER TABLE favoritos DISABLE ROW LEVEL SECURITY;

-- PASO 3: Otorgamos todos los accesos públicos para que tu frontend trabaje libre en local
GRANT ALL ON favoritos TO postgres, anon, authenticated, service_role;