create table public.favoritos (
  id bigint generated by default as identity primary key,
  user_id uuid references auth.users(id) on delete cascade not null,
  producto_id text not null, -- Cambia a bigint o uuid según el tipo de dato de tu tabla de productos
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  
  -- Clave única para evitar que un usuario agregue el mismo producto dos veces
  unique(user_id, producto_id)
);

-- Habilitar Row Level Security (RLS)
alter table public.favoritos enable row level security;

-- Políticas de Seguridad (Seguridad Ivano)
create policy "Usuarios pueden ver sus propios favoritos"
  on public.favoritos for select
  using (auth.uid() = user_id);

create policy "Usuarios pueden agregar sus propios favoritos"
  on public.favoritos for insert
  with check (auth.uid() = user_id);

create policy "Usuarios pueden eliminar sus propios favoritos"
  on public.favoritos for delete
  using (auth.uid() = user_id);