-- Creamos la tabla que guardará la info de tus videos subidos
CREATE TABLE videos_inicio (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    creado_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    titulo TEXT NOT NULL,         -- Ej: 'Sorteo Modelo 120'
    video_path TEXT NOT NULL,     -- Aquí se guarda el nombre del archivo en el Storage
    activo BOOLEAN DEFAULT TRUE,
    orden INT DEFAULT 0
);

-- Habilitamos seguridad para que la web pueda leerla
ALTER TABLE videos_inicio ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Lectura Publica Videos" ON videos_inicio FOR SELECT USING (true);



-- 1. Eliminamos la columna antigua que ya no sirve
ALTER TABLE videos_inicio 
DROP COLUMN IF EXISTS url_red_social;

-- 2. Agregamos las 3 columnas nuevas
-- Las ponemos como 'text' y permitimos que sean NULL por si un video no está en las 3 redes
ALTER TABLE videos_inicio 
ADD COLUMN url_tiktok text,
ADD COLUMN url_instagram text,
ADD COLUMN url_facebook text;