DROP TABLE IF EXISTS variantes_stock CASCADE;
DROP TABLE IF EXISTS modelos CASCADE;

CREATE TABLE modelos (
  id int8 GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nombre_zapatilla text NOT NULL,     -- Ejemplo: Bridge
  descripcion text,                  -- Info detallada
  modelo text,                       -- Ejemplo: Plomo (o la variante de diseño)
  sigla text UNIQUE,                 -- F0123
  color text,
  -- Nota: La talla no va aquí, va en la tabla de stock para no repetir filas
  precio numeric(10, 2) NOT NULL,
  genero text,                       -- Hombre / Mujer / Unisex
  categoria text,
  -- Bloque de imágenes
  imagen_url text,                   -- Foto Principal
  imagen_url_2 text,
  imagen_url_3 text,
  imagen_url_4 text,
  imagen_url_5 text,
  created_at timestamp DEFAULT now()
);

CREATE TABLE variantes_stock (
  id int8 GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  modelo_id int8 REFERENCES modelos(id) ON DELETE CASCADE,
  talla int2 NOT NULL,
  stock int4 DEFAULT 0,
  created_at timestamp DEFAULT now()
);