create table contactos_atencion (
  id bigint generated by default as identity primary key,
  fecha timestamp with time zone default timezone('utc'::text, now()) not null,
  canal text not null, -- WhatsApp, Facebook, Gmail, etc.
  usuario_nombre text, -- Opcional, si quieres pedirlo antes
  mensaje_previo text -- Un resumen o tag del mensaje
);