-- Creamos la tabla para los mensajes del formulario de contacto
CREATE TABLE contactos (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nombre TEXT NOT NULL,
  email TEXT NOT NULL,
  asunto TEXT,
  mensaje TEXT,
  created_at TIMESTAMPTZ DEFAULT NOW()
);