-- 1. Eliminamos las tablas actuales para limpiar el esquema
DROP TABLE IF EXISTS variantes_stock CASCADE;
DROP TABLE IF EXISTS modelos CASCADE;

-- 2. Creamos la tabla Maestra con el orden EXACTO que quieres ver
CREATE TABLE modelos (
  id int8 GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  sigla text UNIQUE,                  -- Ejemplo: F0123
  modelo_nombre text NOT NULL,        -- Ejemplo: Bridge Plomo
  precio numeric(10, 2) NOT NULL,
  descripcion text,
  color text,
  genero text,                        -- Hombre / Mujer / Unisex
  categoria text,
  -- BLOQUE DE IMÁGENES ALINEADO
  imagen_url text,                    -- Foto 1 (Principal)
  imagen_url_2 text,                  -- Foto 2
  imagen_url_3 text,                  -- Foto 3
  imagen_url_4 text,                  -- Foto 4
  imagen_url_5 text,                  -- Foto 5
  created_at timestamp DEFAULT now()
);

-- 3. Creamos la tabla de Stock (Hija)
CREATE TABLE variantes_stock (
  id int8 GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  modelo_id int8 REFERENCES modelos(id) ON DELETE CASCADE,
  talla int2 NOT NULL,                -- 39, 40, 41, 42, 43
  stock int4 DEFAULT 0,
  created_at timestamp DEFAULT now()
);